export const categoryConstansts = {
    GET_ALL_CATEGORIES_REQUEST:' GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:' GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:' GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants = {
    GET_PRODUCTS_BY_SLUG:'GET_PRODUCTS_BY_SLUG',
    GET_PRODUCT_REQUEST:'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE:'GET_PRODUCT_FALI'
}

export const authConstants={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE:" LOGIN_FAILURE",
    LOGIN_SUCCESS:" LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_FAILURE:" LOGOUT_FAILURE",
    LOGOUT_SUCCESS:" LOGOUT_SUCCESS",

}
export const cartConstants = {
    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
    RESET_CART: "RESET_CART",
    ADD_TO_CART:"ADD_TO_CART",
  
    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  };

  export const userConstants = {
    GET_ADDRESS_REQUEST :'GET_ADDRESS_REQUEST',
    GET_ADDRESS_SUCCESS :'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAILURE :'GET_ADDRESS_FAILURE',
    ADD_ADDRESS_REQUEST :'ADD_ADDRESS_REQUEST',
    ADD_ADDRESS_SUCCESS :'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_FAILURE :'ADD_ADDRESS_FAILURE',
};
